safe: false
permalink: /:title
exclude: 
  - 'README.md'

name: Keptab
desc: Kept tabs as tabs group and read them later
tags: Keptab, Keptab Chrome, Keptab Firefox, Keptab Edge, Keptab Safari
link: 'https://keptab.com'

custom:
  links:
    - name: Keptab Blog
      link: https://blog.keptab.com
    
    - name: Keptab Translations
      link: https://translations.keptab.com

apps:
  chrome:
    name: Chrome
    link: https://chrome.google.com/webstore/detail/keptab/feodekcipceogpeomnijgmdlmocbggbi
    version: v0.4
  
  edge:
    name: Edge
    link: https://microsoftedge.microsoft.com/addons/detail/keptab/jhajaihldpgefhccepbjdpiimikplhng
    version: v0.4
  
  firefox:
    name: Firefox
    link: https://addons.mozilla.org/en-US/firefox/addon/keptab/
    version: v0.4
  
  safari:
    name: Safari
    link: https://chrome.google.com/webstore/detail/keptab/feodekcipceogpeomnijgmdlmocbggbi
    version: v0.4
  
  opera:
    name: Opera
    link: https://addons.opera.com/extensions/details/keptab/
    version: v0.4

meta:
  author:
    name: Keptab Team
    email: hi@keptab.com
    about: We create the Project Keptab.

  google:
    gaId: UA-123456-1
    gaDomain: keptab.com
  
  facebook:
    name: Keptab
    link: https://www.facebook.com/keptab
  
  twitter:
    name: Keptab
    link: https://twitter.com/keptab
